### ISSUE TITLE
Compilation error in dependency `tharsis-prof 0.5.2` DMD 2.067.1

### ISSUE THREAD

**Issue by MarisaLovesUsAll** [Circular-Studios/Dash#245]
`OS: WIndows 7 x64`
`dub: 0.9.24-rc.1, built on Jul 13 2015`
`DMD: 2.067.1`
`dash-cli: 0.2.3`

I gave up trying to get old versions of Dash working on DMD 2.067.1, so I'm using `"dash": "~develop"` now, and it still doesn't compile.
I think this is because DMD breaks backward compatibility on every new version.
Also, seems like some dependency packages for old versions does not exist in dub registry. Strange, but `dash~develop` is the only version where `dub upgrade` works.

`C:\Users\lunar\AppData\Roaming\dub\packages\tharsis-prof-0.5.2\source\tharsis\prof\ranges.d(720,24): Error: template instance TypeTuple!(0, 1, 2, 3, 4, 5, 6, 7, 8, 9) template 'TypeTuple' is not defined, did you mean isTypeTuple(T...)?
FAIL
C:\Users\lunar\AppData\Roaming\dub\packages\tharsis-prof-0.5.2\.dub\build\library-debug-windows-x86-dmd_2067-60BE4484605607AE8A8CC8E6ACE413A5\ tharsis-prof staticLibrary
Error executing command run: dmd failed with exit code 1.`

Great work btw. I'm planning to use Dash instead of writing my own framework, if I finally make it works.

**Comment by MarisaLovesUsAll** [comment]
I Initialized project with dash-cli, but default project (`"dash": "~>0.9.0"`) freezes on this stage:

```
D:\Dropbox\GameDesign\ethereal_one\ethereal_one>dub --verbose
Using dub registry url 'http://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json

Looking for local package map at C:\Users\lunar\AppData\Roaming\dub\packages\loc
al-packages.json
Note: Failed to determine version of package dash-game at .. Assuming ~master.
Refreshing local packages (refresh existing: false)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json

Looking for local package map at C:\Users\lunar\AppData\Roaming\dub\packages\loc
al-packages.json
Version selection for dependency dash (dash) of dash-game is missing.
Checking for missing dependencies.
Search for versions of dash (1 package suppliers)
Search for versions of gl3n (1 package suppliers)
Search for versions of derelict-assimp3 (1 package suppliers)
Search for versions of derelict-util (1 package suppliers)
Search for versions of derelict-fi (1 package suppliers)
Search for versions of dyaml (1 package suppliers)
Search for versions of tinyendian (1 package suppliers)
Search for versions of dlogg (1 package suppliers)
Search for versions of colorize (1 package suppliers)
Search for versions of derelict-gl3 (1 package suppliers)
Search for versions of msgpack-d (1 package suppliers)
Search for versions of vibe-d (1 package suppliers)
Search for versions of libevent (1 package suppliers)
Search for versions of openssl (1 package suppliers)
Search for versions of libev (1 package suppliers)
Search for versions of libasync (1 package suppliers)
Search for versions of memutils (1 package suppliers)
Search for versions of botan (1 package suppliers)
Ignoring version specification (~master) for path based dependency ../memutils
Failed to load path based dependency memutils: No package file found in ..\memut
ils\, expected one of dub.json/dub.sdl/package.json
Search for versions of libhttp2 (1 package suppliers)
```

**Comment by MarisaLovesUsAll** [comment]
Dependencies builds successfully on DMD 2.066.1, but engine not.
Here's the log:

```
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\memory.d(81,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\bitop.d(10,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name infile C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\string.d(13,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\stddef.d(13,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\exception.d(12,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\stdio.d(14,1): Error:package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\config.d(14,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\stdarg.d(13,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\stdint.d(13,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\signal.d(13,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\wchar_.d(13,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\time.d(14,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\sys\windows\windows.d(13,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\vararg.d(17,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\stdlib.d(13,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\errno.d(13,1): Error:package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\math.d(12,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\thread.d(12,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\internal\traits.d(9,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\sync\mutex.di(2,1): Error:package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\atomic.d(16,1): Error: package name 'std.experimental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
FAIL .dub\build\application-debug-windows-x86-dmd_2066-E60746923D1C5161D9725627C5E71358\ dash-game executable
Error executing command run:dmd failed with exit code 1.
```

**Comment by MarisaLovesUsAll** [comment]
DMD 2.067.1
Just updated all dependencies to their latest versions. Got «out of memory» error, DMD consumed 4 Gb and crashed.

**Comment by dislogical** [comment]
Thanks for investigating this. Our current reflection solution is pretty heavy on the CTFE usage, so my guess is something changed in DMD that causes it to use a lot more memory, and then it runs out, given that DMD is a 32-bit application. I'm in the process of rewriting the reflection solution to be much lighter, but it may take a few days.

**Comment by MarisaLovesUsAll** [comment]
@ColdenCullen 
Thanks for answer. I'm trying to compile 64-bit DMD now, I'll post my progress here.

**Comment by MarisaLovesUsAll** [comment]
Built 64-bit DMD `2.067.1` with MSVS2013 via `dmd_source\src\dmd_msc_vs10.sln`
DMD Process took ~5 Gb of RAM and successfully compiled dash engine.
Though, it was only engine, the game still doesn't builds.
`dub --verbose` log:

```
Microsoft Windows [Version 6.1.7601]

D:\Dropbox\GameDesign\ethereal_one\ethereal_one>dub -v
Using dub registry url 'http://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json

Looking for local package map at C:\Users\lunar\AppData\Roaming\dub\packages\loc
al-packages.json
Try to load local package map at C:\Users\lunar\AppData\Roaming\dub\packages\loc
al-packages.json
Refreshing local packages (refresh existing: false)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json

Looking for local package map at C:\Users\lunar\AppData\Roaming\dub\packages\loc
al-packages.json
Try to load local package map at C:\Users\lunar\AppData\Roaming\dub\packages\loc
al-packages.json
Version selection for dependency dash-engine (dash-engine) of ethereal-one is mi
ssing.
Checking for missing dependencies.
Search for versions of dash-engine (1 package suppliers)
Search for versions of gl3n (1 package suppliers)
Search for versions of logger (1 package suppliers)
Search for versions of x11 (1 package suppliers)
Search for versions of derelict-assimp3 (1 package suppliers)
Search for versions of derelict-util (1 package suppliers)
Search for versions of colorize (1 package suppliers)
Search for versions of msgpack-d (1 package suppliers)
Search for versions of vibe-d (1 package suppliers)
Search for versions of libevent (1 package suppliers)
Search for versions of openssl (1 package suppliers)
Search for versions of libev (1 package suppliers)
Search for versions of libasync (1 package suppliers)
Search for versions of memutils (1 package suppliers)
Search for versions of derelict-fi (1 package suppliers)
Search for versions of gfm (1 package suppliers)
Search for versions of derelict-enet (1 package suppliers)
Search for versions of ae-graphics (1 package suppliers)
Search for versions of derelict-gl3 (1 package suppliers)
Search for versions of derelict-sdl2 (1 package suppliers)
Search for versions of tharsis-prof (1 package suppliers)
Search for versions of tinyendian (1 package suppliers)
Search for versions of dyaml (1 package suppliers)
```

At this point `dub` freezes for some time. `dub --vverbose` shows a lot of messages about dependencies.

```
Dependency dash-engine -> dyaml >=0.5.1 <0.6.0 mismatches with selected version
invalid (ci=22)
Interation (ci=22) dash-engine 0.12.1, gl3n 1.1.0, logger 0.3.3, x11 1.0.7, dere
lict-assimp3 1.0.1, derelict-util invalid, colorize 1.0.5, msgpack-d 1.0.0-beta.
2, vibe-d 0.7.24-beta.4, libevent invalid, openssl invalid, libev invalid, libas
ync 0.7.5, memutils 0.4.1, derelict-fi 2.0.2, gfm 2.3.28, derelict-enet 2.0.0, a
e-graphics 0.0.5, derelict-gl3 1.0.14, derelict-sdl2 1.9.3, tharsis-prof 0.5.3,
tinyendian invalid, dyaml invalid (C)
Dependency derelict-assimp3 -> derelict-util >=1.0.0 mismatches with selected ve
rsion invalid (ci=5)
Dependency vibe-d -> libevent >=2.0.1+2.0.16 <2.1.0 mismatches with selected ver
sion invalid (ci=9)
Dependency derelict-fi -> derelict-util >=2.0.0 mismatches with selected version
 invalid (ci=14)
Dependency derelict-enet -> derelict-util >=2.0.0 <3.0.0 mismatches with selecte
d version invalid (ci=16)
Dependency derelict-gl3 -> derelict-util >=1.0.3 mismatches with selected versio
n invalid (ci=18)
Dependency derelict-sdl2 -> derelict-util >=1.9.0 mismatches with selected versi
on invalid (ci=19)
Dependency tharsis-prof -> tinyendian >=0.1.1 <0.2.0 mismatches with selected ve
rsion invalid (ci=21)
Dependency dyaml -> tinyendian >=0.1.0 <0.2.0 mismatches with selected version i
nvalid (ci=22)
Interation (ci=22) dash-engine 0.12.1, gl3n 1.1.0, logger 0.3.3, x11 1.0.7, dere
lict-assimp3 1.0.1, derelict-util invalid, colorize 1.0.5, msgpack-d 1.0.0-beta.
2, vibe-d 0.7.24-beta.4, libevent invalid, openssl invalid, libev invalid, libas
ync 0.7.5, memutils 0.4.1, derelict-fi 2.0.2, gfm 2.3.28, derelict-enet 2.0.0, a
e-graphics 0.0.5, derelict-gl3 1.0.14, derelict-sdl2 1.9.3, tharsis-prof 0.5.3,
tinyendian invalid, dyaml 0.5.1 (C)
```

And log ends with:

```
Compiling using dmd...
dmd -c -of.dub\build\application-debug-windows-x86-dmd_2067-F1666500ED124DC186E1
52EC0686F8B9\ethereal-one.obj -debug -g -w -version=DashUseGl3n -version=VibeCus
tomMain -version=VibeLibeventDriver -version=Have_ethereal_one -version=Have_das
h_engine -version=Have_gfm -version=Have_gl3n -version=Have_logger -version=Have
_x11 -version=Have_derelict_assimp3 -version=Have_derelict_util -version=Have_co
lorize -version=Have_msgpack_d -version=Have_vibe_d -version=Have_libevent -vers
ion=Have_openssl -version=Have_derelict_fi -version=Have_gfm_enet -version=Have_
derelict_enet -version=Have_gfm_math -version=Have_gfm_logger -version=Have_gfm_
net -version=Have_gfm_core -version=Have_gfm_assimp -version=Have_gfm_freeimage
-version=Have_gfm_image -version=Have_ae_graphics -version=Have_gfm_opengl -vers
ion=Have_derelict_gl3 -version=Have_gfm_sdl2 -version=Have_derelict_sdl2 -versio
n=Have_tharsis_prof -version=Have_tinyendian -version=Have_dyaml -IScripts -Ilib
s\dash-engine\source -Ilibs\dash-engine\third_party\DWinProgramming -IC:\Users\l
unar\AppData\Roaming\dub\packages\gl3n-1.1.0 -IC:\Users\lunar\AppData\Roaming\du
b\packages\logger-0.3.3 -IC:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3
.3\std -IC:\Users\lunar\AppData\Roaming\dub\packages\logger-0.3.3\std\experiment
al\logger -IC:\Users\lunar\AppData\Roaming\dub\packages\x11-1.0.7\source -IC:\Us
ers\lunar\AppData\Roaming\dub\packages\derelict-assimp3-1.0.1\source -IC:\Users\
lunar\AppData\Roaming\dub\packages\derelict-util-2.0.1\source -IC:\Users\lunar\A
ppData\Roaming\dub\packages\colorize-1.0.5\source -IC:\Users\lunar\AppData\Roami
ng\dub\packages\msgpack-d-1.0.0-beta.2\src -IC:\Users\lunar\AppData\Roaming\dub\
packages\vibe-d-0.7.24-beta.4\source -IC:\Users\lunar\AppData\Roaming\dub\packag
es\libevent-2.0.1_2.0.16 -IC:\Users\lunar\AppData\Roaming\dub\packages\openssl-1
.1.4_1.0.1g -IC:\Users\lunar\AppData\Roaming\dub\packages\derelict-fi-2.0.2\sour
ce -IC:\Users\lunar\AppData\Roaming\dub\packages\gfm-2.3.28\enet -IC:\Users\luna
r\AppData\Roaming\dub\packages\derelict-enet-2.0.0\source -IC:\Users\lunar\AppDa
ta\Roaming\dub\packages\gfm-2.3.28\math -IC:\Users\lunar\AppData\Roaming\dub\pac
kages\gfm-2.3.28\logger -IC:\Users\lunar\AppData\Roaming\dub\packages\gfm-2.3.28
\net -IC:\Users\lunar\AppData\Roaming\dub\packages\gfm-2.3.28\core -IC:\Users\lu
nar\AppData\Roaming\dub\packages\gfm-2.3.28\assimp -IC:\Users\lunar\AppData\Roam
ing\dub\packages\gfm-2.3.28\freeimage -IC:\Users\lunar\AppData\Roaming\dub\packa
ges\gfm-2.3.28\image -IC:\Users\lunar\AppData\Roaming\dub\packages\ae-graphics-0
.0.7 -IC:\Users\lunar\AppData\Roaming\dub\packages\gfm-2.3.28\opengl -IC:\Users\
lunar\AppData\Roaming\dub\packages\derelict-gl3-1.0.14\source -IC:\Users\lunar\A
ppData\Roaming\dub\packages\gfm-2.3.28\sdl2 -IC:\Users\lunar\AppData\Roaming\dub
\packages\derelict-sdl2-1.9.6\source -IC:\Users\lunar\AppData\Roaming\dub\packag
es\tharsis-prof-0.5.3\source -IC:\Users\lunar\AppData\Roaming\dub\packages\tinye
ndian-0.1.2\source -IC:\Users\lunar\AppData\Roaming\dub\packages\dyaml-0.5.1\sou
rce -J. Scripts\game.d libs\dash-engine\source\dash\core\main.d C:\Users\lunar\A
ppData\Roaming\dub\packages\vibe-d-0.7.24-beta.4\source\vibe\appmain.d
C:\D64\bin\..\import\core\stdc\stdio.d(16): Error: package name 'std.experimenta
l.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppD
ata\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\stdc\config.d(13): Error: package name 'std.experiment
al.logger.core' conflicts with usage as a module name in file C:\Users\lunar\App
Data\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\stdc\stddef.d(15): Error: package name 'std.experiment
al.logger.core' conflicts with usage as a module name in file C:\Users\lunar\App
Data\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\stdc\stdarg.d(13): Error: package name 'std.experiment
al.logger.core' conflicts with usage as a module name in file C:\Users\lunar\App
Data\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\stdc\stdint.d(15): Error: package name 'std.experiment
al.logger.core' conflicts with usage as a module name in file C:\Users\lunar\App
Data\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\stdc\signal.d(15): Error: package name 'std.experiment
al.logger.core' conflicts with usage as a module name in file C:\Users\lunar\App
Data\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\stdc\wchar_.d(15): Error: package name 'std.experiment
al.logger.core' conflicts with usage as a module name in file C:\Users\lunar\App
Data\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\stdc\time.d(16): Error: package name 'std.experimental
.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppDa
ta\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\sys\windows\windows.d(13): Error: package name 'std.ex
perimental.logger.core' conflicts with usage as a module name in file C:\Users\l
unar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\exception.d(12): Error: package name 'std.experimental
.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppDa
ta\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\stdc\errno.d(15): Error: package name 'std.experimenta
l.logger.core' conflicts with usage as a module name in file C:\Users\lunar\AppD
ata\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\stdc\string.d(15): Error: package name 'std.experiment
al.logger.core' conflicts with usage as a module name in file C:\Users\lunar\App
Data\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\sys\windows\winsock2.d(7): Error: package name 'std.ex
perimental.logger.core' conflicts with usage as a module name in file C:\Users\l
unar\AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\bitop.d(10): Error: package name 'std.experimental.log
ger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\R
oaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\stdc\stdlib.d(15): Error: package name 'std.experiment
al.logger.core' conflicts with usage as a module name in file C:\Users\lunar\App
Data\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\vararg.d(17): Error: package name 'std.experimental.lo
gger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\
Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\atomic.d(16): Error: package name 'std.experimental.lo
gger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\
Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\thread.d(12): Error: package name 'std.experimental.lo
gger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\
Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\internal\traits.d(9): Error: package name 'std.experim
ental.logger.core' conflicts with usage as a module name in file C:\Users\lunar\
AppData\Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
C:\D64\bin\..\import\core\memory.d(81): Error: package name 'std.experimental.lo
gger.core' conflicts with usage as a module name in file C:\Users\lunar\AppData\
Roaming\dub\packages\logger-0.3.3\std\experimental\logger\core.d
FAIL .dub\build\application-debug-windows-x86-dmd_2067-F1666500ED124DC186E152EC0
686F8B9\ ethereal-one executable
Error executing command run:
dmd failed with exit code 1.
Full exception: object.Exception@source\dub\compilers\compiler.d(270): dmd faile
d with exit code 1.
```

It' the same errors about `logger`. I'll continue tomorrow.

**Comment by dislogical** [comment]
First of all, thanks again for helping with this issue!

I think the `logger` issue is probably because Dash still depends on the [`logger`](http://code.dlang.org/packages/logger) package, which is conflicting with `std.exipiremental.logger`, added in D-Programming-Language/phobos#1500. That should be solvable by just removing `logger` as a dash dependency.

**Comment by MarisaLovesUsAll** [comment]
`gfm` depends on `logger`, `dash` depends on `gfm`. So I need to build all dependencies (or at least gfm) locally, without logger.
Didn't have much time, I'll post my progress later.

**Comment by dislogical** [comment]
Sounds good. I've also opened d-gamedev-team/gfm#124, so hopefully they can get their ducks in a row properly.

**Comment by MarisaLovesUsAll** [comment]
@ColdenCullen they did something with logger, will you try to fix this issue? Engine still doesn't work thanks to dub.

**Comment by dislogical** [comment]
Yeah, I'm working on it. The problem is that the current component serialization system is _very_ CTFE memory intensive, and will require a redesign/rebuild, which will probably take a lot of time. 

For now, your best bet is probably to stick with 2.066.1, and then upgrade to 2.068.x once the new system is ready.
